[FIX] Improve the design of readme file and add contributors section.
gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords pull request #54
Opened 2023-10-14 19:08 UTC by Freakyab

[FIX] Improve the design of readme file and add contributors section. 

Resolve issue 
#53

2023-10-14 19:10 UTC, gauravsingh1281 commented
@Freakyab Show me the screenshot

2023-10-14 19:14 UTC, Freakyab commented
> @Freakyab Show me the screenshot

https://github.com/Freakyab/Rentalog-Rent-Management-Web-App-For-Landlords/blob/main/README.md

2023-10-14 19:19 UTC, gauravsingh1281 commented
> > @Freakyab Show me the screenshot
> 
> https://github.com/Freakyab/Rentalog-Rent-Management-Web-App-For-Landlords/blob/main/README.md

Don't change the text or information which are written in the original readme file. Try to redesign it and make it more catchy or engaging.

2023-10-14 19:35 UTC, Freakyab commented
> > > @Freakyab Show me the screenshot
> > 
> > 
> > https://github.com/Freakyab/Rentalog-Rent-Management-Web-App-For-Landlords/blob/main/README.md
> 
> Don't change the text or information which are written in the original readme file. Try to redesign it and make it more catchy or engaging.

for making it catchy, I have added keywords otherwise the content is same. Also added Contributors names to readme file.

2023-10-15 14:59 UTC, gauravsingh1281 requested changes
This text are different from original one

2023-10-15 15:03 UTC, gauravsingh1281 requested changes
don't touch the text which is written in the original file

2023-10-15 15:03 UTC, gauravsingh1281 commented on README.md
> +<p>Welcome to Rentalog, the avant-garde web application designed to elevate the way landlords manage their rental properties. Rentalog empowers landlords by seamlessly organizing crucial information
this

2023-10-15 15:03 UTC, gauravsingh1281 commented on README.md
> +## Features 🚀
this

2023-10-28 04:38 UTC, gauravsingh1281 commented
closes via #106

2023-10-28 04:38 UTC, closed without merging